In [1]:
import pandas as pd

df = pd.read_excel("online food delivery.xlsx")
df.head()

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Unnamed: 13
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,Yes

In [2]:
df.shape

(388, 14)

In [3]:
df.columns

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'Customer Type',
       'latitude', 'longitude', 'Pin code', 'Output', 'Feedback',
       'Unnamed: 13'],
      dtype='object')

In [4]:
df.isnull().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
Customer Type                 0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
Unnamed: 13                   0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(103)

In [7]:
df = df.drop_duplicates()

In [8]:
df.shape

(285, 14)

In [9]:
Unnamed: 13

In [11]:
df = df.drop(columns=["Unnamed: 13"])

In [12]:
df.head

<bound method NDFrame.head of      Age  Gender Marital Status Occupation   Monthly Income  \
0     20  Female         Single    Student        No Income
1     24  Female         Single    Student   Below Rs.10000
2     22    Male         Single    Student   Below Rs.10000
3     22  Female         Single    Student        No Income
4     22    Male         Single    Student   Below Rs.10000
..   ...     ...            ...        ...              ...
355   21    Male         Single    Student        No Income
363   31    Male        Married   Employee  More than 50000
369   30    Male        Married   Employee  More than 50000
374   21    Male         Single    Student        No Income
386   23    Male         Single    Student   Below Rs.10000

    Educational Qualifications  Family size Customer Type  latitude  \
0                Post Graduate            4      Frequent   12.9766
1                     Graduate            3       Regular   12.9770
2                Post Graduate            3       Regular   12.9551
3                     Graduate            6      Frequent   12.9473
4                Post Graduate            4      Frequent   12.9850
..                         ...          ...           ...       ...
355                   Graduate            2       Regular   13.0012
363                       Ph.D            3       Regular   12.9306
369              Post Graduate            6      Frequent   12.9369
374                   Graduate            3       Regular   13.0641
386              Post Graduate            2       Regular   12.9770

     longitude  Pin code Output   Feedback
0      77.5993    560001    Yes   Positive
1      77.5773    560009    Yes   Positive
2      77.6593    560017    Yes  Negative
3      77.5616    560019    Yes   Positive
4      77.5533    560010    Yes   Positive
..         ...       ...    ...        ...
355    77.5995    560046     No   Positive
363    77.5434    560085    Yes   Positive
369    77.6407    560095    Yes   Positive
374    77.5931    560092    Yes  Negative
386    77.5773    560009    Yes   Positive

[285 rows x 13 columns]>

In [16]:
df.to_excel("Cleaned_Online_Food_Delivery.xlsx", index=False)